package ca.drdc.ivct.fom.warfare;

import ca.drdc.ivct.fom.base.structs.*;

/**
 * Communicates information associated with the impact or detonation of a munition.
 */
public class MunitionDetonation {
    /**
     * The set of articulated parts affected by the detonation (including where on the articulated part the detonation has affected).
     */
    private ArticulatedParameterStruct[] articulatedPartData;
    /**
     * The location, in world coordinates, at which the munition detonated.
     */
    private WorldLocationStruct detonationLocation;
    /**
     * The type of detonation (including no detonation).
     */
    private byte detonationResultCode;
    /**
     * An ID, generated by the issuing federate, used to associate related fire and detonation events.
     */
    private EventIdentifierStruct eventIdentifier;
    /**
     * The object instance ID of the entity that fired the munition.
     * This must reference a valid Object instance.
     */
    private String firingObjectIdentifier;
    /**
     * The velocity vector of the munition at the moment of the detonation.
     */
    private VelocityVectorStruct finalVelocityVector;
    /**
     * The type of fuse on the munition.
     */
    private int fuseType;
    /**
     * The Object instance ID of the fired munition, if an object instance is registered.
     * If there is no object instance associated with the parameter, then this should be
     * set to the empty string (no characters). Refer to SISO-STD-001 section 7.8.6 for handling empty strings.
     */
    private String munitionObjectIdentifier;
    /**
     * The type of munition that is detonating.
     */
    private EntityTypeStruct munitionType;
    /**
     * The number of rounds fired in the burst.
     */
    private int quantityFired;
    /**
     * The rate of fire in rounds per minute when quantity > 1. Zero otherwise.
     */
    private int rateOfFire;
    /**
     * The location of the detonation in coordinates relative to the target entity (if any).
     */
    private RelativePositionStruct relativeDetonationLocation;
    /**
     * The object instance ID of the entity that the munition has detonated on (if any).
     * If there is no object instance associated with the parameter, then this should be
     * set to the empty string (no characters). Refer to SISO-STD-001 section 7.8.6 for handling empty strings.
     */
    private String targetObjectIdentifier;
    /**
     * The type of warhead on the munition.
     */
    private int warheadType;

    public MunitionDetonation() {
    }

    public MunitionDetonation(
        ArticulatedParameterStruct[] articulatedPartData,
        WorldLocationStruct detonationLocation,
        byte detonationResultCode,
        EventIdentifierStruct eventIdentifier,
        String firingObjectIdentifier,
        VelocityVectorStruct finalVelocityVector,
        int fuseType,
        String munitionObjectIdentifier,
        EntityTypeStruct munitionType,
        int quantityFired,
        int rateOfFire,
        RelativePositionStruct relativeDetonationLocation,
        String targetObjectIdentifier,
        int warheadType
    ) {
        this.articulatedPartData = articulatedPartData;
        this.detonationLocation = detonationLocation;
        this.detonationResultCode = detonationResultCode;
        this.eventIdentifier = eventIdentifier;
        this.firingObjectIdentifier = firingObjectIdentifier;
        this.finalVelocityVector = finalVelocityVector;
        this.fuseType = fuseType;
        this.munitionObjectIdentifier = munitionObjectIdentifier;
        this.munitionType = munitionType;
        this.quantityFired = quantityFired;
        this.rateOfFire = rateOfFire;
        this.relativeDetonationLocation = relativeDetonationLocation;
        this.targetObjectIdentifier = targetObjectIdentifier;
        this.warheadType = warheadType;
    }

    public ArticulatedParameterStruct[] getArticulatedPartData() {
        return articulatedPartData;
    }

    public void setArticulatedPartData(ArticulatedParameterStruct[] articulatedPartData) {
        this.articulatedPartData = articulatedPartData;
    }

    public WorldLocationStruct getDetonationLocation() {
        return detonationLocation;
    }

    public void setDetonationLocation(WorldLocationStruct detonationLocation) {
        this.detonationLocation = detonationLocation;
    }

    public byte getDetonationResultCode() {
        return detonationResultCode;
    }

    public void setDetonationResultCode(byte detonationResultCode) {
        this.detonationResultCode = detonationResultCode;
    }

    public EventIdentifierStruct getEventIdentifier() {
        return eventIdentifier;
    }

    public void setEventIdentifier(EventIdentifierStruct eventIdentifier) {
        this.eventIdentifier = eventIdentifier;
    }

    public String getFiringObjectIdentifier() {
        return firingObjectIdentifier;
    }

    public void setFiringObjectIdentifier(String firingObjectIdentifier) {
        this.firingObjectIdentifier = firingObjectIdentifier;
    }

    public VelocityVectorStruct getFinalVelocityVector() {
        return finalVelocityVector;
    }

    public void setFinalVelocityVector(VelocityVectorStruct finalVelocityVector) {
        this.finalVelocityVector = finalVelocityVector;
    }

    public int getFuseType() {
        return fuseType;
    }

    public void setFuseType(int fuseType) {
        this.fuseType = fuseType;
    }

    public String getMunitionObjectIdentifier() {
        return munitionObjectIdentifier;
    }

    public void setMunitionObjectIdentifier(String munitionObjectIdentifier) {
        this.munitionObjectIdentifier = munitionObjectIdentifier;
    }

    public EntityTypeStruct getMunitionType() {
        return munitionType;
    }

    public void setMunitionType(EntityTypeStruct munitionType) {
        this.munitionType = munitionType;
    }

    public int getQuantityFired() {
        return quantityFired;
    }

    public void setQuantityFired(int quantityFired) {
        this.quantityFired = quantityFired;
    }

    public int getRateOfFire() {
        return rateOfFire;
    }

    public void setRateOfFire(int rateOfFire) {
        this.rateOfFire = rateOfFire;
    }

    public RelativePositionStruct getRelativeDetonationLocation() {
        return relativeDetonationLocation;
    }

    public void setRelativeDetonationLocation(RelativePositionStruct relativeDetonationLocation) {
        this.relativeDetonationLocation = relativeDetonationLocation;
    }

    public String getTargetObjectIdentifier() {
        return targetObjectIdentifier;
    }

    public void setTargetObjectIdentifier(String targetObjectIdentifier) {
        this.targetObjectIdentifier = targetObjectIdentifier;
    }

    public int getWarheadType() {
        return warheadType;
    }

    public void setWarheadType(int warheadType) {
        this.warheadType = warheadType;
    }

    @Override
    public String toString() {
        return String.format(
            "MunitionDetonation [Id=%s At=(Location=%s Target=%s) Type=%s]",
            eventIdentifier,
            detonationLocation,
            targetObjectIdentifier,
            munitionType
        );
    }
}
